version: '3'
services:
  # mongo:
  #   image: mongo
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=mongo
  #     - MONGO_INITDB_ROOT_PASSWORD=password
  #   volumes:
  #     - mongo-db:/data/db
  #   ports:
  #     - '27017:27017'
  client:
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # depends_on:
    #   - mongo
    networks:
      - appNetwork
    # environment:
    #   - MONGO_USER=mongo
    #   - MONGO_PASSWORD=password
    #   - MONGO_IP=localhost
      # - MONGO_PORT=27017
  event-bus:
    build:
      context: event-bus
      dockerfile: Dockerfile
    ports:
      - "4009:4009"
    # depends_on:
    #   - mongo
    networks:
      - appNetwork
    # environment:
    #   - MONGO_USER=mongo
    #   - MONGO_PASSWORD=password
    #   - MONGO_IP=localhost
      # - MONGO_PORT=27017
  auth:
    build:
      context: Auth
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    # depends_on:
    #   - mongo
    networks:
      - appNetwork
    # environment:
    #   - MONGO_USER=mongo
    #   - MONGO_PASSWORD=password
    #   - MONGO_IP=localhost
    #   - MONGO_PORT=27017
  classrooms:
    build:
      context: Classrooms
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    # depends_on:
    #   - mongo
    networks:
      - appNetwork
    # environment:
    #   - MONGO_USER=mongo
    #   - MONGO_PASSWORD=password
    #   - MONGO_IP=localhost
      # - MONGO_PORT=27017
  post:
    build:
      context: Post
      dockerfile: Dockerfile
    ports:
      - "4002:4002"
    # depends_on:
    #   - mongo
    networks:
      - appNetwork
    # environment:
    #   - MONGO_USER=mongo
    #   - MONGO_PASSWORD=password
    #   - MONGO_IP=localhost
    #   - MONGO_PORT=27017

networks:
  appNetwork:
    driver: bridge

# volumes:
#   mongo-db:
